[package]
name = "dual-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-rt = { path = "../../rt" }
pico-hal = { path = "../../hal" }
util = { path = "../../util" }
aligned = "0.4.2"
