[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lock_api = "0.4.11"

[dev-dependencies]
array-init = "2.1.0"
rand = "0.8.5"
